name: Automerge version bumps

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

env:
  GIT_AUTHOR_NAME: henriquesilverio

jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approving
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == ${{ env.GIT_AUTHOR_NAME }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  automerge:
    needs: [autoapprove]
    runs-on: ubuntu-latest
    steps:
      - name: Auto merging
        uses: pascalgn/automerge-action@v0.7.5
        if: github.actor == ${{ env.GIT_AUTHOR_NAME }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_LOGIN: ${{ env.GIT_AUTHOR_NAME }}
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "10000"
