name: Release @next

on:
  push:
    branches:
      - next

env:
  GIT_AUTHOR_NAME: henriquesilverio
  GIT_AUTHOR_EMAIL: henrique-silverio@hotmail.com

jobs:
  release:
    name: Release new @next version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: next
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Run tests suites
        run: npm test
      - name: Get version before release step
        id: preversion
        run: echo "::set-output name=version::$(npm run get-version --silent)"
      - name: Release to GitHub and GitHub Packages
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ env.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ env.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ env.GIT_AUTHOR_EMAIL }}
        run: npm run release
      - name: Get version after release step
        id: posversion
        run: echo "::set-output name=version::$(npm run get-version --silent)"
      - name: Pull Request with updated package metadata
        if: steps.preversion.outputs.version != steps.posversion.outputs.version
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: 'chore(release): v${{ steps.posversion.outputs.version }}'
          committer: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          title: 'chore(release): v${{ steps.posversion.outputs.version }}'
          body: 'Version bump in `package.json` and `package-lock.json` for release [v${{ steps.posversion.outputs.version }}](https://github.com/${{github.repository}}/releases/tag/v${{ steps.posversion.outputs.version }})'
          branch: version-bump/v${{ steps.posversion.outputs.version }}
